### ISSUE TITLE
Difference in output between R and Python file

### ISSUE THREAD

**Issue by ArchithSharma** [ArchithSharma/TAMS-Mock-Election#2]
Whenever Election.py is run, it outputs one less vote than in Election.R in the Senate election.

**Comment by TamoghnaN** [comment]
There seems to also be another problem with the python file where you cannot run the file due to some errors with renaming the columns and rows

**Comment by ArchithSharma** [comment]
Yeah, I noticed that today as well. Thanks for catching it.
